apiVersion: batch/v1
kind: Job
metadata:
  name: logto-db-migration
  labels:
    app: logto
    app.kubernetes.io/name: logto
    app.kubernetes.io/component: db-migration
  annotations:
    argocd.argoproj.io/sync-wave: "1" # 第二阶段：数据库就绪后执行迁移
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: logto
        app.kubernetes.io/component: db-migration
    spec:
      restartPolicy: Never
      containers:
      - name: db-migration
        image: ghcr.io/logto-io/logto:latest
        command:
        - sh
        - -c
        - |
          npm run cli db seed -- --swe && npm run cli db alteration deploy latest
        env:
        # Database connection - Directly use the CNPG generated URI
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: logto-postgres-app
              key: uri
        - name: CI
          value: "true" # Non-interactive mode
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
