apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: logto-backup-storage-credentials
spec:
  encryptedData:
    ACCESS_KEY_ID: <sealed-encrypted-data-prod>
    ACCESS_SECRET_KEY: <sealed-encrypted-data-prod>
  template:
    metadata:
      name: logto-backup-storage-credentials
    type: Opaque
