apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logto-postgres-cluster-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # 先部署数据库
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/your-org/your-repo.git
    targetRevision: main
    path: kustomize/logto-postgres-cluster/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
